name: anonymous_chat
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.8.1
  openpgp: ^3.8.3
  custom_refresh_indicator: ^4.0.1
  oauth2_client: ^3.3.0
  shared_preferences: ^2.3.4
  flutter_secure_storage: ^9.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  icons_launcher: ^3.0.0

icons_launcher:
  image_path: 'assets/images/appicon.png'
  platforms:
    android:
      enable: true
    ios:
      enable: true
    linux:
      enable: true
    windows:
      enable: true
    macos:
      enable: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/
